### ISSUE TITLE
Skipping submodule update in corner case

### ISSUE THREAD

**Issue by bgranzow** [SNLComputation/CApp#2]
For a given package `foo`, if the remote `HEAD` of the package is at the same SHA as the one specified in `package.cmake`, certain checkout logic is skipped, because CApp assumes the package has already been successfully checked out. This is likely only an issue for fresh builds. Namely, the build I am interested in fails because `git submodule update --init --recursive` was skipped.

Example output when the `HEAD` SHA differs from the one specified in `package.cmake`

```
debug: in foo, existing_remotes=origin
debug: foo remote origin has URL git@github.com:foo/foo.git
debug: foo remote origin matches desired URL git@github.com:foo/foo.git
debug: in foo pointing_refs=
debug: checked out commit SHA explicitly
debug: submodule update of foo completed
debug: checkout of foo succeeded
debug: clone of foo succeeded
```

Example output when the `HEAD` SHA is the same as `package.cmake` from an initial call to `build`

```
debug: foo is already at the desired commit
debug: clone of foo succeeded
```

**Comment by ibaned** [comment]
I think I fixed this? Closing based on that assumption, please comment if it isn't really fixed!
